name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
      
    - name: Install dependencies
      run: npm ci && npm install -g @ionic/cli native-run cordova-res

    - name: Ionic build
      run: ionic cap sync

      
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Build with Gradle
      run:  cd android && chmod +x ./gradlew && ./gradlew build --no-daemon
  
    
    - name: Show build
      run: ls android/app/build/outputs/apk/release
